### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/iot-sitewise-datasource#189]
Work from this comment https://github.com/grafana/iot-sitewise-datasource/pull/179#discussion_r1190933637

Sample PR: https://github.com/grafana/iot-sitewise-datasource/pull/190

Test files
- [ ] pkg/resource/caching_resource_provider_test.go
- [ ] pkg/server/test/describe_asset_model_test.go
- [ ] pkg/server/test/describe_asset_test.go
- [ ] pkg/server/test/list_asset_models_test.go
- [ ] pkg/server/test/list_assets_test.go
- [ ] pkg/server/test/list_associated_assets_test.go
- [ ] pkg/server/test/property_value_history_test.go
- [ ] pkg/server/test/property_values_for_time_range_test.go

Once test files are refactored, the following helpers, test data can be removed as they won't be used anymore
- [ ] pkg/sitewise/api/test_data_test.go
- [ ] pkg/testdata
```[tasklist]
### Tasks
```

**Comment by fridgepoet** [comment]
If it's clear to you which tests remain to be refactored, would you add a checklist or something?

**Comment by katebrenner** [comment]
closing as not planned
